pipeline {
    agent any
    environment {
      VERSION = "1.0.0"
    }
    triggers {
        githubPush()
    }
    stages {
        stage('Checkout repo'){
           steps{
               checkout scm
            }
         }
        stage('Restore'){
           steps{
            script {
               sh "dotnet restore ConsoleApp/ConsoleApp.sln --configuration Release"
              }
            }
         }
        stage('Build'){
           steps{
            script {
              sh "dotnet build /p:PackageVersion=${VERSION} ConsoleApp/ConsoleApp.sln --configuration Release --no-restore"
              }
            }
         }
        stage('Test: Unit Test'){
           steps {
                sh 'dotnet test ConsoleApp/UnitTestProject/UnitTestProject.csproj --configuration Release --no-restore'
             }
          }
    }
}