pipeline {
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Checkout repo'){
           steps{
               checkout scm
            }
         }
        stage('Clean'){
           steps{
               sh 'dotnet clean ConsoleApp.sln --configuration Release'
            }
         }
        stage('Build'){
           steps{
               sh 'dotnet build ConsoleApp.sln --configuration Release --no-restore'
            }
         }
        stage('Test: Unit Test'){
           steps {
                sh 'dotnet test UnitTestProject/UnitTestProject.csproj --configuration Release --no-restore'
             }
          }
    }
}